[package]
name = "egui-table-kit"
description = "An extension for `egui` that brings batteries-included, filtering, highlighting, tree structures, and an action dispatch to your tables."
version = "0.1.2"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/egui-table-kit"
repository = "https://github.com/xangelix/egui-table-kit"
authors = ["Cody Wyatt Neiman (xangelix) <neiman@cody.to>"]
categories = [
    "gui",
    "visualization",
    "data-structures",
    "algorithms",
    "rust-patterns",
]
keywords = ["egui", "table", "tree", "filter", "sort"]

[dependencies]
ahash = "0.8"
bitflags = { version = "2", features = ["serde"] }
compact_str = "0.9"
egui = "0.34"
egui_extras = { version = "0.34", default-features = false }
fluent-zero = "0.1"
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }
regex = "1.12"
roaring = { version = "0.11", features = ["serde", "simd"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[build-dependencies]
fluent-zero-build = "0.1.4"

[dev-dependencies]
eframe = "0.34.3"
